### ISSUE TITLE
Food instructions

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/WhiskerWatch#7]
# Description:
Allow users to select multiple food instructions using dropdown or other components in the WhiskerWatch app. This will enable users to easily choose and manage various food instructions for their cats. Users should be able to add custom instructions if needed.

## Tasks:
- [ ] Update the frontend form for adding and editing a cat to include multiple choices for food instructions.
- [ ] Implement logic to handle the selection and deselection of food instructions.
- [ ] Update the backend API to handle multiple food instructions for each cat.

## Relevant data
```
const foodInstructionsOptions = [
  'Feed Twice Daily',
  'Use Specific Food Brand',
  'Portion Control Instructions',
  'Monitor Food Consumption',
  'Avoid Certain Foods',
  'Add Supplements',
  'Introduce New Foods Gradually',
  'Use Food Puzzles for Enrichment',
  'Check for Allergies or Sensitivities',
];
```
