### ISSUE TITLE
Water instructions

### ISSUE THREAD

**Issue by Noelierx** [Noelierx/WhiskerWatch#8]
# Description:
Allow users to select multiple water instructions using dropdown or other components in the WhiskerWatch app. This will enable users to choose and manage various water instructions for their cats. Users should be able to add custom instructions if needed.

## Tasks:
- [ ] Update the frontend form for adding and editing a cat to include multiple choices for water instructions.
- [ ] Implement logic to handle the selection and deselection of water instructions.
- [ ] Update the backend API to handle multiple water instructions for each cat.

## Relevant data
```
const waterInstructionsOptions = [
  'Refill Water Bowl Twice Daily',
  'Monitor Water Consumption',
  'Use Filtered Water Only',
  'Change Water Daily',
  'Add Ice Cubes in Summer',
  'Add Water Fountain',
  'Keep Water Bowl Away from Food',
  'Use Stainless Steel Bowls',
  'Keep Water Level Consistent',
  'Check for Dehydration Signs',
  'Use Water Additives',
];
```
